### ISSUE TITLE
Ability to open calendars towards left rather than right

### ISSUE THREAD

**Issue by jayakrishnankk** [fetrarij/ngx-daterangepicker-material#21]
I am trying to use this calendar in my project. But my calendar selection is on the right hand side of the screen. When the calendar is opened, it doesn't have space to show both calendars when the widget opens towards right. Can we add a parameter with which we can open calendar towards left rather than on right.

expected param: `[opens]="left"`

**Comment by praveenpuglia** [comment]
For a quick workaround, in a global css somewhere, you can do this...
```css
.md-drppicker {
    left: -300px; /* whatever suits you the best value */
    transform-origin: 100% 0;
}
```
