### ISSUE TITLE
How to change color?

### ISSUE THREAD

**Issue by rachel9955** [fetrarij/ngx-daterangepicker-material#97]
Is there a way to change the main color of the date picker? it's default is #3f51b5.
![capture](https://user-images.githubusercontent.com/46649224/51985832-8c178200-24a7-11e9-93a4-31b124579718.PNG)

thanks.

**Comment by fetrarij** [comment]
Hello, You can custom the style easily, our class are all inside .md-drppicker

eg, in your style.scss you can add:

```css
.md-drppicker {
    .btn {
        background-color: red !important;
    }
}
```

look here #62
